### ISSUE TITLE
Multiple file transfer at a time

### ISSUE THREAD

**Issue by sandipchandra17** [kirillzyusko/react-native-wifi-p2p#30]
Is it possible to send mutiple files to receiver using this library?
Scenario is receiver will click one time in the receive file button and sender select multiple file and send at one go..

**Comment by kirillzyusko** [comment]
Hm, I never thought about it.
But once again, you can use the trick with sending message, which contains all required information.
For example you can create own methods sendMultipleFiles(files[])/receiveMultipleFiles()

Let's consider next flow (how these functions may be implemented):
1. Server calls `receiveMessage()`
2. Client calls `sendMessage(JSON.stringify({ filesCount: files.length }))`
3. After receiving the message server trying to parse the message: `const { filesCount } = JSON.parse(message)`;
4. Then server execute next cycle: `for (let i = 0; i < filesCount; i++) { await receiveFile() }`
5. And client also in cycle send all files: `for (let i = 0; i < files.length; i++) { await sendFile(files[i]) }`

**Comment by sandipchandra17** [comment]
In which file need to create these methods.

**Comment by kirillzyusko** [comment]
You can create it in your project :)
It shouldn't be included in this library I think.
If it's needed in your project - create own set of functions.
Because every project is unique. And requirements for every project is also unique.
The purpose of this library is providing set of functions, which are written on the top of native API.
I wouldn't like to cover all cases in one library, since API will contain a lot of methods and it may be hard to support.
I hope I answered on your question☺️

**Comment by sandipchandra17** [comment]
Thanks I will try in my react native code..

**Comment by kirillzyusko** [comment]
Thanks. I will close this issue.
Feel free to re-open, if needed.
